### ISSUE TITLE
Vert.x 4 has futurized API

### ISSUE THREAD

**Issue by tsegismont** [LarsEckart/vertx-local-context-data-example#1]
https://github.com/LarsEckart/vertx-local-context-data-example/blob/022f8abc26779d15c648ee2245acd1ffa8605d7e/src/main/java/com/larseckart/vertx/example/example/MainVerticle.java#L18-L25

In Vert.x 4 you no longer need to create a promise and use it as callback. There are futurized versions of asynchronous methods.

**Comment by LarsEckart** [comment]
took me a bit to figure out what you mean there, but now I got it and updated my code (in my other project where i took it from to create this example). :)
